### ISSUE TITLE
HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by smg28** [nightflyer73/plugin.video.sportube#1]
Hi,
it seems the url "http://rest2.sportube.tv/api/default/tv.jsonp" in the file "default.py" doesn't work in Kodi. 

The log:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "C:\myDir\Kodi\addons\plugin.video.sportube\default.py", line 51, in <module>
                                                show_root_menu()
                                              File "C:\myDir\Kodi\addons\plugin.video.sportube\default.py", line 35, in show_root_menu
                                                data = urllib2.urlopen(url).read()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(_args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(_args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--

ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sportube/

ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sportube/) failed

**Comment by nightflyer73** [comment]
Upstream changed API. I need to adapt the plugin.
